### ISSUE TITLE
是否也曾考虑添加照片裁剪功能

### ISSUE THREAD

**Issue by houshengbo** [gmajian/sandphoto#4]
首先非常感谢作者gmajian的创意。这种照片拍版还是非常稀缺有用，同时赞赏作者作为技术通道的才华。
我在这里提出的一个问题不算是bug了，而是一个功能的扩展。

不知道作者可否想过添加照片的裁剪功能。一个有类似功能的的网站可以参考：https://www.idphoto4you.com/
这个网站既可以裁剪照片也可以拍版。谢谢。

**Comment by gmajian** [comment]
谢谢你的意见， 我会考虑添加类似的功能。
