### ISSUE TITLE
求助：部署到 windows 2012 R2 + IIS上后生成的图片有问题

### ISSUE THREAD

**Issue by joelz** [gmajian/sandphoto#6]
首先感谢您的代码。很好用！

说说我的问题。我把代码部署到了vps上（地址在这里：http://photo-size.dc1979.com/test.php ）。vps的环境是windows 2012 R2 + IIS + PHP 7.2。目前网站可以正常运行，也可以生成图片。但是我发现生成的图片有些问题，无法预览，也没有exif信息，类似这样：
![image](https://user-images.githubusercontent.com/469974/86736931-7b891500-c066-11ea-89f6-b346da237303.png)

正常应该是这样的：
![image](https://user-images.githubusercontent.com/469974/86737053-8fcd1200-c066-11ea-926b-e5c9e3b3439a.png)

请问您知道是我哪里配置错了吗？是我的PHP安装有问题？还是我的代码改错了？（我fork的代码在这里：https://github.com/joelz/sandphoto ）

期待收到您的答复。谢谢！

附上我的php.ini：
[php.ini.zip](https://github.com/gmajian/sandphoto/files/4883246/php.ini.zip)

**Comment by gmajian** [comment]
我的php用的gd的相关信息，请参考一下：（linux的）

![image](https://user-images.githubusercontent.com/4533398/91632114-7758e400-e993-11ea-8c9d-980d4e0446c4.png)

你可以看一下你的phpinfo()

**Comment by joelz** [comment]
请问你的php是什么版本的？

**Comment by gmajian** [comment]
PHP Version 7.2.24-0ubuntu0.18.04.6

**Comment by gmajian** [comment]
close the old issue
