### ISSUE TITLE
可以部署到Cloudflare Workers吗？

### ISSUE THREAD

**Issue by wuge0** [gmajian/sandphoto#7]
没有服务器

**Comment by gmajian** [comment]
貌似Cloudflare Workers不支持PHP， 你可以考虑其它的云服务， 比如阿里云，AWS， Azure. Azure App Service 支持php: https://docs.microsoft.com/zh-cn/azure/app-service/quickstart-php?pivots=platform-linux

**Comment by wuge0** [comment]
可以转换成html代码吗？
